-- Tabloya eksik sütunları ekliyoruz
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Studies' AND COLUMN_NAME = 'ReportText')
BEGIN
    ALTER TABLE Studies ADD ReportText NVARCHAR(MAX) NULL;
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Studies' AND COLUMN_NAME = 'ReportDate')
BEGIN
    ALTER TABLE Studies ADD ReportDate DATETIME NULL;
END